# Generated by Django 4.2.1 on 2023-05-19 04:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_partido', models.CharField(max_length=50, unique=True)),
                ('Sigla', models.CharField(max_length=6, unique=True)),
                ('Slogan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('ci', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cuenta', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('informacion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(70000000), django.core.validators.MaxValueValidator(79999999)])),
                ('longitud', models.CharField(blank=True, max_length=80, null=True)),
                ('latitud', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuenta.partidoelectoral')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
