# Generated by Django 4.2.1 on 2023-05-14 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('carnet_identidad', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('contraseña', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PadronElectoral',
            fields=[
                ('nro_padron', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cuenta.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_partido', models.CharField(max_length=50, unique=True)),
                ('Sigla', models.CharField(max_length=6, unique=True)),
                ('Slogan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_votacion', models.CharField(choices=[('A', 'Normal'), ('B', 'Mixto')], default='B', max_length=1)),
                ('inicio_votacion', models.DateTimeField()),
                ('fin_votacion', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_padron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.padronelectoral')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.candidato')),
                ('ci_votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuenta.usuario')),
                ('id_votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.votacion')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_votos', models.IntegerField()),
                ('estado_result', models.CharField(choices=[('G', 'Ganador'), ('P', 'Perdedor')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.candidato')),
                ('id_votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.votacion')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='id_partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.partidoelectoral'),
        ),
        migrations.AddConstraint(
            model_name='padronelectoral',
            constraint=models.UniqueConstraint(fields=('nro_padron', 'ci_usuario'), name='unique_migration_host_combination'),
        ),
    ]
