# Generated by Django 4.2.1 on 2023-05-19 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadronElectoral',
            fields=[
                ('nro_padron', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_votacion', models.CharField(choices=[('A', 'Normal'), ('B', 'Mixto')], default='B', max_length=1)),
                ('inicio_votacion', models.DateTimeField()),
                ('fin_votacion', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_padron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.padronelectoral')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL)),
                ('ci_votante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votante', to=settings.AUTH_USER_MODEL)),
                ('id_votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.votacion')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_votos', models.IntegerField()),
                ('estado_result', models.CharField(choices=[('G', 'Ganador'), ('P', 'Perdedor')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.votacion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='padronelectoral',
            constraint=models.UniqueConstraint(fields=('nro_padron', 'ci_usuario'), name='unique_migration_host_combination'),
        ),
    ]
