# Generated by Django 4.2.1 on 2023-05-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Votacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
