# Generated by Django 4.2.1 on 2023-06-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='cant_vblanco',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='cant_vnullo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='cant_votos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='cant_vpositivo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='total_votos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
