# Generated by Django 4.2.1 on 2023-06-23 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Votacion', '0003_votacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='tipo_votacion',
            field=models.CharField(choices=[('N', 'Normal'), ('M', 'MayoriaAbsoluta'), ('P', 'Proporcional')], default='N', max_length=1),
        ),
        migrations.CreateModel(
            name='Referendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('pregunta', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio_referendum', models.DateTimeField(blank=True, null=True)),
                ('fin_referendum', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('padron_electoral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Votacion.padronelectoral')),
            ],
        ),
    ]
