# Generated by Django 4.2.1 on 2023-07-01 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Votacion', '0004_alter_votacion_tipo_votacion_referendum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoReferendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_vsi', models.IntegerField(blank=True, default=0, null=True)),
                ('cant_vblanco', models.IntegerField(blank=True, default=0, null=True)),
                ('cant_vno', models.IntegerField(blank=True, default=0, null=True)),
                ('cant_vnullo', models.IntegerField(blank=True, default=0, null=True)),
                ('total_votos', models.IntegerField(blank=True, default=0, null=True)),
                ('ganador', models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('A', 'Abstencion'), ('B', 'Blanco'), ('U', 'Nulo')], default='B', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_referendum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.referendum')),
            ],
        ),
        migrations.CreateModel(
            name='VotoReferendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashvoto', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_voto', models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('A', 'Abstencion'), ('B', 'Blanco'), ('U', 'Nulo')], default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_votante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elector', to=settings.AUTH_USER_MODEL)),
                ('id_referendum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.referendum')),
            ],
        ),
        migrations.AddField(
            model_name='resultado',
            name='escanio_asig',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='votacion',
            name='escanio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voto',
            name='hashvoto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VotoReferendum_extended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votoref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.votoreferendum')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoReferendum_extended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.resultadoreferendum')),
            ],
        ),
        migrations.CreateModel(
            name='Referendum_extended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referendum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votacion.referendum')),
            ],
        ),
    ]
